#!/usr/bin/env python3
"""Side-by-side benchmark comparison: Python stack vs Rust stack.

Usage:
    python scripts/bench_compare.py <python_results.txt> <rust_results.txt>

Output:
    Markdown table + JSON summary saved to docs/bench_comparison.json
"""

import json
import re
import sys
from pathlib import Path

SCENARIO_RE = re.compile(r"^\[(.+)\]")
RPS_RE = re.compile(r"rps\s*[:=]\s*([\d.]+)", re.IGNORECASE)
OK_RE = re.compile(r"ok\s*[:=]\s*(\d+)", re.IGNORECASE)
ERRORS_RE = re.compile(r"errors?\s*[:=]\s*(\d+)", re.IGNORECASE)


def parse_results(path: str) -> dict[str, dict[str, float]]:
    results: dict[str, dict[str, float]] = {}
    current: str | None = None
    with open(path) as f:
        for line in f:
            m = SCENARIO_RE.match(line.strip())
            if m:
                current = m.group(1)
                results[current] = {"rps": 0.0, "ok": 0.0, "errors": 0.0}
                continue
            if current is None:
                continue
            if (r := RPS_RE.search(line)):
                results[current]["rps"] = float(r.group(1))
            if (r := OK_RE.search(line)):
                results[current]["ok"] = float(r.group(1))
            if (r := ERRORS_RE.search(line)):
                results[current]["errors"] = float(r.group(1))
    return results


def find_scenario(key: str, results: dict[str, dict[str, float]]) -> tuple[str, dict[str, float]] | None:
    if key in results:
        return key, results[key]
    for name, metrics in results.items():
        if name.startswith(key):
            return name, metrics
    return None


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: bench_compare.py <python.txt> <rust.txt>")
        sys.exit(1)

    py_file, rs_file = sys.argv[1], sys.argv[2]
    py = parse_results(py_file)
    rs = parse_results(rs_file)

    all_keys = sorted(set(list(py.keys()) + list(rs.keys())))

    rows: list[dict] = []
    print("\n## Python vs Rust Benchmark Comparison\n")
    print(f"{'Scenario':<45} {'Python RPS':>12} {'Rust RPS':>12} {'Speedup':>10} {'Rust Errors':>12}")
    print("-" * 95)

    for key in all_keys:
        py_match = find_scenario(key, py)
        rs_match = find_scenario(key, rs)

        py_rps = py_match[1]["rps"] if py_match else 0.0
        rs_rps = rs_match[1]["rps"] if rs_match else 0.0
        rs_errors = rs_match[1]["errors"] if rs_match else 0.0

        speedup = rs_rps / py_rps if py_rps > 0 else float("inf")
        speedup_str = f"{speedup:.2f}x" if py_rps > 0 else "N/A"

        label = key[:44]
        print(f"{label:<45} {py_rps:>12.1f} {rs_rps:>12.1f} {speedup_str:>10} {rs_errors:>12.0f}")

        rows.append({
            "scenario": key,
            "python_rps": py_rps,
            "rust_rps": rs_rps,
            "speedup": round(speedup, 2) if py_rps > 0 else None,
            "rust_errors": rs_errors,
        })

    print()

    # Aggregate totals
    py_total = sum(r["python_rps"] for r in rows if "aggregate" not in r["scenario"].lower())
    rs_total = sum(r["rust_rps"] for r in rows if "aggregate" not in r["scenario"].lower())
    agg_speedup = rs_total / py_total if py_total > 0 else 0
    print(f"{'TOTAL (excl. aggregate)':<45} {py_total:>12.1f} {rs_total:>12.1f} {agg_speedup:>9.2f}x")

    # Save JSON
    summary = {
        "_comment": "Generated by scripts/bench_compare.py — Python vs Rust stack comparison",
        "python_file": py_file,
        "rust_file": rs_file,
        "scenarios": rows,
        "totals": {
            "python_rps": round(py_total, 1),
            "rust_rps": round(rs_total, 1),
            "speedup": round(agg_speedup, 2),
        },
    }
    out = Path("docs/bench_comparison.json")
    out.write_text(json.dumps(summary, indent=2))
    print(f"\nComparison saved to {out}")


if __name__ == "__main__":
    main()
